export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_CART = "FETCH_CART";
export const FETCH_SALES = "FETCH_SALES";
export const FETCH_ORDERS = "FETCH_ORDERS";
export const PLACE_ORDERS = "PLACE_ORDERS";
export const FETCH_FAVORITE_PRODUCTS = "FETCH_FAVORITE_PRODUCTS";
export const FETCH_VIEWED_PRODUCTS = "FETCH_VIEWED_PRODUCTS";
export const FETCH_USERS = "FETCH_USERS";
